export const REPLACE_MISSING_IMAGES = 'REPLACE_MISSING_IMAGES';
export const SUBMIT_FILTERS = 'SUBMIT_FILTERS';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const INITIAL_SEARCH = 'INITIAL_SEARCH';
export const SCROLL_SEARCH = 'SCROLL_SEARCH';
