export const REPLACE_MISSING_IMAGES = 'REPLACE_MISSING_IMAGES';
export const SUBMIT_FILTERS = 'SUBMIT_FILTERS';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const TRIGGER_ACTION = 'TRIGGER_ACTION';
